version: 2

project_name: terraform-provider-fleets

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: fleets
    binary: terraform-provider-fleets
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{ .Version }}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: provider
    ids:
      - fleets
    formats:
      - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"

signs:
  - artifacts: checksum
    args:
      - --batch
      - --local-user
      - "{{ .Env.GPG_FINGERPRINT }}"
      - --armor
      - --detach-sign
      - "${artifact}"

release:
  github:
    owner: trycua
    name: terraform-provider-fleets
