// Code generated by cmd/generate-pool-resource; DO NOT EDIT.

package provider

import (
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type poolResourceModel struct {
	ID                 types.String         `tfsdk:"id"`
	Name               types.String         `tfsdk:"name"`
	Namespace          types.String         `tfsdk:"namespace"`
	Replicas           types.Int64          `tfsdk:"replicas"`
	CPUCores           types.Int64          `tfsdk:"cpu_cores"`
	Memory             types.String         `tfsdk:"memory"`
	ContainerDiskImage types.String         `tfsdk:"container_disk_image"`
	ImagePullSecret    types.String         `tfsdk:"image_pull_secret"`
	Runtime            types.String         `tfsdk:"runtime"`
	Firmware           types.String         `tfsdk:"firmware"`
	ReadinessProbeJSON jsontypes.Normalized `tfsdk:"readiness_probe_json"`
	LivenessProbeJSON  jsontypes.Normalized `tfsdk:"liveness_probe_json"`
	Phase              types.String         `tfsdk:"phase"`
	TotalCount         types.Int64          `tfsdk:"total_count"`
	AvailableCount     types.Int64          `tfsdk:"available_count"`
	ClaimedCount       types.Int64          `tfsdk:"claimed_count"`
	Services           types.Set            `tfsdk:"service"`
	Autoscaling        types.Object         `tfsdk:"autoscaling"`
}

type serviceModel struct {
	Name       types.String `tfsdk:"name"`
	TargetPort types.Int64  `tfsdk:"target_port"`
	Protocol   types.String `tfsdk:"protocol"`
}

type autoscalingModel struct {
	MinPoolSize     types.Int64 `tfsdk:"min_pool_size"`
	InitialPoolSize types.Int64 `tfsdk:"initial_pool_size"`
	MaxPoolSize     types.Int64 `tfsdk:"max_pool_size"`
}

func poolResourceSchema() schema.Schema {
	return schema.Schema{Description: "A Cyclops computer-use pool. The pool name also owns its same-named namespace.",
		Attributes: map[string]schema.Attribute{
			"id":                   schema.StringAttribute{Computed: true},
			"name":                 schema.StringAttribute{Required: true, Description: "DNS label used for both pool and namespace.", Validators: []validator.String{stringvalidator.LengthBetween(1, 63), stringvalidator.RegexMatches(dnsLabelRegex, "must be a lowercase DNS label")}, PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"namespace":            schema.StringAttribute{Computed: true},
			"replicas":             schema.Int64Attribute{Required: true, Validators: []validator.Int64{int64validator.AtLeast(0)}},
			"cpu_cores":            schema.Int64Attribute{Required: true, Validators: []validator.Int64{int64validator.AtLeast(1)}},
			"memory":               schema.StringAttribute{Required: true},
			"container_disk_image": schema.StringAttribute{Required: true},
			"image_pull_secret":    schema.StringAttribute{Optional: true, Computed: true, Description: "Kubernetes image pull secret. Defaults to ecr-credentials."},
			"runtime":              schema.StringAttribute{Optional: true, Computed: true, Description: "Pool backend. \"kubevirt\" (default) provisions a KubeVirt\nVM. \"macos\" provisions a macOS sandbox (ADMIN-ONLY\n— the cyclops-cs backend rejects macos pool writes from\nnon-admins; the SPA hides the option). Flows verbatim\nthrough the compat shim into the OSGymSandboxTemplate\nvmTemplate, where macos_backend dispatches on it.", Validators: []validator.String{stringvalidator.OneOf("gvisor", "kubevirt", "macos")}},
			"firmware":             schema.StringAttribute{Optional: true, Computed: true, Description: "VM firmware. Use \"efi\" for GPT/UEFI-only guest images\n(e.g. the dockur-built Windows desktop-workspace);\n\"bios\" is KubeVirt's default and what the Linux\nworkspace images boot with.", Validators: []validator.String{stringvalidator.OneOf("bios", "efi")}},
			"readiness_probe_json": schema.StringAttribute{Optional: true, CustomType: jsontypes.NormalizedType{}, Description: "JSON object for the VMI readinessProbe."},
			"liveness_probe_json":  schema.StringAttribute{Optional: true, CustomType: jsontypes.NormalizedType{}, Description: "JSON object for the VMI livenessProbe."},
			"phase":                schema.StringAttribute{Computed: true},
			"total_count":          schema.Int64Attribute{Computed: true},
			"available_count":      schema.Int64Attribute{Computed: true},
			"claimed_count":        schema.Int64Attribute{Computed: true},
		},
		Blocks: map[string]schema.Block{
			"service": schema.SetNestedBlock{NestedObject: schema.NestedBlockObject{Attributes: map[string]schema.Attribute{
				"name":        schema.StringAttribute{Required: true, Description: "Service name suffix (sandbox name is prepended)."},
				"target_port": schema.Int64Attribute{Required: true, Description: "Port on the VM pod to forward to.", Validators: []validator.Int64{int64validator.Between(1, 65535)}},
				"protocol":    schema.StringAttribute{Optional: true, Computed: true, Validators: []validator.String{stringvalidator.OneOf("TCP", "UDP")}},
			}}},
			"autoscaling": schema.SingleNestedBlock{Attributes: map[string]schema.Attribute{
				"min_pool_size":     schema.Int64Attribute{Optional: true, Computed: true, Description: "ScaledObject minReplicaCount — the durable warm\nfloor kept while the extension is enabled. 0 lets\nthe pool scale to zero when there are no claims.", Validators: []validator.Int64{int64validator.AtLeast(0)}},
				"initial_pool_size": schema.Int64Attribute{Optional: true, Computed: true, Description: "One-time warm head-start: the pool-operator seeds\nspec.replicas to this when the pool is created so\nthe first claims bind without a cold start. KEDA\nthen owns spec.replicas; the value decays toward\nthe live claim demand (floored at minPoolSize)\nonce KEDA begins polling.", Validators: []validator.Int64{int64validator.AtLeast(0)}},
				"max_pool_size":     schema.Int64Attribute{Required: true, Description: "ScaledObject maxReplicaCount — hard ceiling.", Validators: []validator.Int64{int64validator.AtLeast(1)}},
			}},
		},
	}
}

func serviceObjectType() map[string]attr.Type {
	return map[string]attr.Type{"name": types.StringType, "target_port": types.Int64Type, "protocol": types.StringType}
}

func autoscalingObjectType() map[string]attr.Type {
	return map[string]attr.Type{"min_pool_size": types.Int64Type, "initial_pool_size": types.Int64Type, "max_pool_size": types.Int64Type}
}

var dnsLabelRegex = regexp.MustCompile(`^[a-z0-9]([-a-z0-9]*[a-z0-9])?$`)
