// Code generated by cmd/generate-pool-resource; DO NOT EDIT.

package provider

import (
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type poolResourceModel struct {
	ID                     types.String         `tfsdk:"id"`
	Name                   types.String         `tfsdk:"name"`
	Namespace              types.String         `tfsdk:"namespace"`
	Replicas               types.Int64          `tfsdk:"replicas"`
	CPUCores               types.Int64          `tfsdk:"cpu_cores"`
	Memory                 types.String         `tfsdk:"memory"`
	ContainerDiskImage     types.String         `tfsdk:"container_disk_image"`
	ImagePullSecret        types.String         `tfsdk:"image_pull_secret"`
	Runtime                types.String         `tfsdk:"runtime"`
	Firmware               types.String         `tfsdk:"firmware"`
	ReadinessProbeJSON     jsontypes.Normalized `tfsdk:"readiness_probe_json"`
	LivenessProbeJSON      jsontypes.Normalized `tfsdk:"liveness_probe_json"`
	Command                types.List           `tfsdk:"command"`
	Args                   types.List           `tfsdk:"args"`
	Env                    types.Map            `tfsdk:"env"`
	ProcessMode            types.String         `tfsdk:"process_mode"`
	ClaimSecrets           types.Bool           `tfsdk:"claim_secrets"`
	TTLSecondsAfterCreated types.Int64          `tfsdk:"ttl_seconds_after_created"`
	IdleTTLSeconds         types.Int64          `tfsdk:"idle_ttl_seconds"`
	TTLPolicy              types.String         `tfsdk:"ttl_policy"`
	TemplateName           types.String         `tfsdk:"template_name"`
	CurrentReplicas        types.Int64          `tfsdk:"current_replicas"`
	ReadyReplicas          types.Int64          `tfsdk:"ready_replicas"`
	Services               types.Set            `tfsdk:"service"`
	Autoscaling            types.Object         `tfsdk:"autoscaling"`
}

type serviceModel struct {
	Name       types.String `tfsdk:"name"`
	TargetPort types.Int64  `tfsdk:"target_port"`
	Protocol   types.String `tfsdk:"protocol"`
}

type autoscalingModel struct {
	MinPoolSize     types.Int64 `tfsdk:"min_pool_size"`
	InitialPoolSize types.Int64 `tfsdk:"initial_pool_size"`
	MaxPoolSize     types.Int64 `tfsdk:"max_pool_size"`
}

func poolResourceSchema() schema.Schema {
	return schema.Schema{Description: "A Cua Fleet computer-use pool: an OSGymSandboxWarmPool and its OSGymSandboxTemplate. The pool name also owns its same-named namespace.",
		Attributes: map[string]schema.Attribute{
			"id":                        schema.StringAttribute{Computed: true},
			"name":                      schema.StringAttribute{Required: true, Description: "DNS label used for both pool and namespace.", Validators: []validator.String{stringvalidator.LengthBetween(1, 63), stringvalidator.RegexMatches(dnsLabelRegex, "must be a lowercase DNS label")}, PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"namespace":                 schema.StringAttribute{Computed: true},
			"replicas":                  schema.Int64Attribute{Optional: true, Computed: true, Description: "Desired number of pre-warmed OSGymSandboxes.", Validators: []validator.Int64{int64validator.AtLeast(0)}},
			"cpu_cores":                 schema.Int64Attribute{Required: true, Validators: []validator.Int64{int64validator.AtLeast(1)}},
			"memory":                    schema.StringAttribute{Required: true},
			"container_disk_image":      schema.StringAttribute{Required: true, Description: "KubeVirt containerDisk OCI image (runtime=kubevirt) or the sandbox pod image ref (runtime=macos/gvisor)."},
			"image_pull_secret":         schema.StringAttribute{Optional: true, Description: "Kubernetes image pull secret. Omit this argument for anonymous public-image pulls."},
			"runtime":                   schema.StringAttribute{Optional: true, Computed: true, Description: "Pool backend runtime. \"kubevirt\" (default) reconciles each sandbox into a KubeVirt VM. \"macos\" reconciles it into a macOS sandbox (an agent-sandbox Sandbox on a macOS node); \"gvisor\" into a gVisor (runsc) pod on the gVisor K3s workers (also an agent-sandbox Sandbox). For the pod runtimes containerDiskImage is the pod image ref and firmware/cpuCores/memory are advisory.", Validators: []validator.String{stringvalidator.OneOf("gvisor", "kubevirt", "macos")}},
			"firmware":                  schema.StringAttribute{Optional: true, Computed: true, Description: "VM firmware. Use \"efi\" for GPT/UEFI-only guest images (e.g. the dockur-built Windows desktop-workspace); \"bios\" is KubeVirt's default and what the Linux workspace images boot with.", Validators: []validator.String{stringvalidator.OneOf("bios", "efi")}},
			"readiness_probe_json":      schema.StringAttribute{Optional: true, CustomType: jsontypes.NormalizedType{}, Description: "JSON object for the VMI readinessProbe."},
			"liveness_probe_json":       schema.StringAttribute{Optional: true, CustomType: jsontypes.NormalizedType{}, Description: "JSON object for the VMI livenessProbe."},
			"command":                   schema.ListAttribute{Optional: true, ElementType: types.StringType, Description: "Entrypoint command (Kubernetes command semantics: replaces the image ENTRYPOINT). Pod runtimes (gvisor/macos) run it on the sandbox container. KubeVirt runs it only with processMode: Run (as /etc/cua/command.sh under cua-command.service, through the sandbox's cloud-init); without it KubeVirt ignores command, as it always has."},
			"args":                      schema.ListAttribute{Optional: true, ElementType: types.StringType, Description: "Arguments (Kubernetes args semantics: they replace the image CMD and follow vmTemplate.command). Runs on pod runtimes (gvisor/macos). On runtime kubevirt it needs processMode: Run and a command (a VM image has no entrypoint to pass them to); without Run the gateway and the pool-operator refuse it."},
			"env":                       schema.MapAttribute{Optional: true, ElementType: types.StringType, Description: "Plain environment variables for the sandbox's command (not for secrets: the values are stored in the template and visible to anyone who can read it). Names must match ^[A-Za-z_][A-Za-z0-9_]*$. $(NAME) references in command/args expand as in Kubernetes. Pod runtimes (gvisor/macos) set them on the sandbox container. On runtime kubevirt they need processMode: Run and go to /etc/cua/env (root, 0600) and the command's environment; values must be single-line there. Without Run the gateway and the pool-operator refuse env on kubevirt."},
			"process_mode":              schema.StringAttribute{Optional: true, Description: "How command, args and env reach the sandbox. Absent or Legacy: unchanged behavior (pod runtimes run them; KubeVirt ignores command and refuses args and env). Run: every runtime runs them with the same semantics. Pod runtimes set them on the sandbox container; KubeVirt writes /etc/cua/env (0600), /etc/cua/command.sh (0700) and cua-command.service into the sandbox's cloud-init Secret, which the guest re-reads on every boot, so warm VMs get it on return-to-pool too. KubeVirt Run needs a Linux guest with cloud-init and systemd.", Validators: []validator.String{stringvalidator.OneOf("Legacy", "Run")}},
			"claim_secrets":             schema.BoolAttribute{Optional: true, Description: "Opt in to claim-scoped secret delivery (OSGymSandboxClaim spec.secretRef). The pool-operator gives every sandbox an operator-owned Secret, empty while the sandbox is warm, fills it when a claim binds and wipes it on release, so a warm sandbox receives its claimant's secrets without a restart. Pod runtimes mount it read-only as a directory (never subPath) at /run/cua, root-owned, mode 0600; the image keeps its default root user, and its root token-sync helper hands the token to a non-root driver. KubeVirt shares it over virtiofs as tag cua-claim-secrets (the EnableVirtioFsConfigVolumes feature gate is GA from KubeVirt v1.8; older KubeVirt needs it enabled); the guest image mounts that tag read-only at /run/cua. cua-env-driver images enable their await-token mode only when /run/cua is a mount point, so the key env-token becomes /run/cua/env-token. Claims with a secretRef fail on templates without this flag."},
			"ttl_seconds_after_created": schema.Int64Attribute{Optional: true, Description: "Creation-age TTL in seconds. When absent, the resource is not automatically reaped based on age.", Validators: []validator.Int64{int64validator.Between(0, 4294967295)}},
			"idle_ttl_seconds":          schema.Int64Attribute{Optional: true, Description: "Idle TTL in seconds. The pool-operator deletes the pool once it has had no Pending or Bound claims for this long, measured from status.lastActivityTime (or creation when no claim was ever made), when OSGYM_POOL_LIFECYCLE_MODE is enforce. When absent, the pool is never reaped for being idle.", Validators: []validator.Int64{int64validator.Between(0, 4294967295)}},
			"ttl_policy":                schema.StringAttribute{Optional: true, Description: "What expiry of ttlSecondsAfterCreated or idleTtlSeconds deletes. Retain (the behaviour when absent) deletes only the pool. Cascade also deletes the pool's dead unbound claims (TTL passed and older than max(900s, bindDeadline)); it never deletes Bound claims, the namespace or volumes.", Validators: []validator.String{stringvalidator.OneOf("Cascade", "Retain")}},
			"template_name":             schema.StringAttribute{Computed: true, Description: "Name of the OSGymSandboxTemplate backing this pool."},
			"current_replicas":          schema.Int64Attribute{Computed: true, Description: "Sandboxes the warm pool currently owns."},
			"ready_replicas":            schema.Int64Attribute{Computed: true, Description: "Sandboxes that are ready to be claimed."},
		},
		Blocks: map[string]schema.Block{
			"service": schema.SetNestedBlock{NestedObject: schema.NestedBlockObject{Attributes: map[string]schema.Attribute{
				"name":        schema.StringAttribute{Required: true, Description: "Service name suffix (sandbox name is prepended)."},
				"target_port": schema.Int64Attribute{Required: true, Description: "Port on the VM pod to forward to.", Validators: []validator.Int64{int64validator.Between(1, 65535)}},
				"protocol":    schema.StringAttribute{Optional: true, Computed: true, Validators: []validator.String{stringvalidator.OneOf("TCP", "UDP")}},
			}}},
			"autoscaling": schema.SingleNestedBlock{Attributes: map[string]schema.Attribute{
				"min_pool_size":     schema.Int64Attribute{Optional: true, Computed: true, Description: "ScaledObject minReplicaCount — the durable warm\nfloor kept while the extension is enabled. 0 lets\nthe pool scale to zero when there are no claims.", Validators: []validator.Int64{int64validator.AtLeast(0)}},
				"initial_pool_size": schema.Int64Attribute{Optional: true, Computed: true, Description: "One-time warm head-start: the pool-operator seeds\nspec.replicas to this when the pool is created so\nthe first claims bind without a cold start. KEDA\nthen owns spec.replicas; the value decays toward\nthe live claim demand (floored at minPoolSize)\nonce KEDA begins polling.", Validators: []validator.Int64{int64validator.AtLeast(0)}},
				"max_pool_size":     schema.Int64Attribute{Optional: true, Computed: true, Description: "ScaledObject maxReplicaCount — hard ceiling.", Validators: []validator.Int64{int64validator.AtLeast(1)}},
			}},
		},
	}
}

func serviceObjectType() map[string]attr.Type {
	return map[string]attr.Type{"name": types.StringType, "target_port": types.Int64Type, "protocol": types.StringType}
}

func autoscalingObjectType() map[string]attr.Type {
	return map[string]attr.Type{"min_pool_size": types.Int64Type, "initial_pool_size": types.Int64Type, "max_pool_size": types.Int64Type}
}

var dnsLabelRegex = regexp.MustCompile(`^[a-z0-9]([-a-z0-9]*[a-z0-9])?$`)
